name: flutter_app
description: AutoARMask Studio - AR Virtual Camera Desktop App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  web_socket_channel: ^2.4.0
  image: ^4.1.3
  provider: ^6.1.2
  http: ^1.2.0
  path_provider: ^2.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/styles/
